import pickle

labels_grouped = {
    "N/A": [
         'empy',
         '-',
         'empty',
         'none',
         'nothing',
         'empty space',
         'no data',
    ],
    "requirements": [
        # synomyms
        'required skill',
        'required skills',
        'capabilities',
        'skills',
        'skill',
        'requirements',
        "applicant's abilities",
        'actual requirements',
        'wished skills',
        'requirements ',
        'requirement',
        'competence',
        'skill requirement',
        'skill exception',
        "candidate's requirements",
        'prerequisite studies',
        'requirement ',
        'formal requirements',
        'job requirements',
        'important requirements',
        'job specific requirements',
        'common requirements',
        # semantics
        'start of skills list',
        'skills heading',
        'checklist for requirements ',
        'requirements title',
        # sub category: software / IT
        'html5',
        'user-testing',
        'prototyping',
        'programming languages',
        'programming',
        'programming skills',
        'software development',
        'mobile development',
         'software developer',
        # sub category: language skills
        'language requirement',
        'languages',
        'langugage skills',
        'language requirements',
        'language',
        'language skill',
        'language skills',
        # sub category: specific tools / skills
        'web services integration',
        'software',
        'mgmt',
        'agile',
        'a360',
        'istqb',
        'bugtracking tool',
        'tools',
        'manollo',
        'clojure',
        'java',
        'scala',
        'design', # memory design
        'thread programming',
        'mobile',
        'spring',
        'angularjs',
        # preferred requirements
        'additional skills',
        'bonus skills',
        'desired skill',
        # soft skills
        "applicant's personality",
        'personal',
        'soft skills',
        'personal skill',
        'social skills',
        'characteristics',
        'habits',
        'character',
        'attitude',

        'transaction management',
        'technical skills',
        'domain skill',
        'project management',
        'quality assurance',
        'analysis',
        'tracking',
        'testing',
        'communication skill',
        'communication skills',
        'communication',
        'repeated'
    ],
    "expectations / qualifications": [
        'travel requirements',
        'traveling requirements',
        'travel',
        'expected values',
        'time commitment',
        'time',
        "company's needs",
        'performance',
        'employee qualities ',
        'degree',
        'job specific tag',
        'knwoledge',
        'education',
        'knowledge',
        'capability',
        'expectations',
        'background',
        'job challenge',
        'business-minded',
        'qualifications',
        'asset'
    ],
    "knowledge and experience": [
        'innovation',
        'tech',
        'experience requirement',
        'experience',
        'integration experience',
        'previous experience',
        'work experience'
    ],
    "meta information": [
        'job id',
        'number',
        'job number'
    ],
    "measurable job expectations": [
        'working hours',
        'detailed info'
    ],
    "measurable facts about the job": [
        'location of job',
        'finlandjob',
        'location ',
        'job location',
        'where',
        'location data',
        'sijainti', # location
        'paikka', # place
        'place',
        'office',
        'job ad',
        'location',
        'finland',

        'duration',
        'time frame',
        'dates',
        'starting date',
        'time period',
        'conditions'
    ],
    "info about job": [
        'intro',
        'job description',
        'job position',
        'description',
        'general',
        'job info',
        'general job description',
        'basic info',
        'job introduction ',
        'introduction',
        'general task',
        'general task ',
        'job',
        'job related field',
        'announcement',
        'announcement ',
        'about',
        'job description ',
        'overview',
        'position description',
        'job desription',
        'position',
        'kuvaus', # description
        'high level summary',
        'summary',
        'global work',
        'software integrations',
        'customer experience'
    ],
    "additional info": [
        'employer listing',
        'more about position',
        'further info',
        'further information',
        'more information',
        'futrher information',
        'lisätieto', # 'Additional information'
        'more info',
        'additional information',
        'link'
    ],
    "job type (time)": [
        'full time',
        'temps',
        'job form',
        'job classification ',
        'extent',
        'position type',
        'job duration ',
        'job type',
        'employment type',
        'work type'
    ],
    "info about the employer": [
        'company',
        'company info',
        'introduction to organization',
        'company description',
        'company ',
        "employer's information",
        'general company info',
        'history of employer',
        'company description ',
        'company facts',
        'organisatio',
        'employer info',
        'employer description',
        'website of employer',
        'website contact info',
        'website',
        'employer listing ',
        'service offering',
        'product line',
        'detailed information on productline',
        'company introduction',
        'intro to company',
        'who',
        'company presentation',
        'organization',
        'ccompany details',
        'company details',
        'organisation description',
        'about us',
        'company data',

        'industry',
        'field of operations',
        'retail',
        'business type',
        'consulting',
        'employer',
        'money games'
    ],
    "company values": [
        'non-discrimination',
        'equal opportunity',
        'company vision',
        'company culture',
        'company policy'
    ],
    "semantic identifiers": [
        'start of list',
        'heading',
        'section title',
        'header',
        'introductory phrase ',
        'transition',
        'subheader',
        'headline',
        'question'
    ],
    "judgement / emotional response": [
        '90% bullshit',
        'blabla',
        'signal for interview question',
        'bullshit',
        'useless info',
        'crap'
    ],
    "role / tasks / responsibilites": [
        'functions',
        'responsibilities heading',
        'role',
        'job role',
        'detailed task',
        'about the role',
        'duties',
        'checklist for job description ',
        'general tasks',
        'job responsibilities',
        'work summary',
        'task titles',
        'responsibilites',
        'main tasks',
        'tasks',
        'responsibility',
        'responsibilities',
        'task'
    ],
    "position / unit in company": [
        'team',
        'unit',
        'unit description',
        'team title',
        'company branch',
        'level',
        'asw',
        'practicalities',
        'position level',
        'department',
        'organisational position',
        'unit of the company',
        'unit of company',
        'company unit descriptions'
    ],
    "company name": [
         'manpower',
         'bayer',
         'bayer2013',
         'bayerr&d',
         'bayerrecruiting ',
         'kemira',
         'reaktor',
         'company name',
         'tieto',
         'paf'
    ],
    "application practicalities": [
        'applying',
        'contract',
        'selection',
        'apply',
        'how to apply',
        'apply info',
        'application process',
        'application information',
        'application practicalities ',
        'practical information',
        'application instructions',
        'how to apply?',
        'instructions',
        # procedure
        'application submission',
        'application',
        'application procedure',
        'attachments',
        'application details',
        # dates
        'opening date',
        'closing date',
        'deadline ',
        'deadline for application',
        'dealine',
        'application deadline',
        'deadline',
        'timetable',

        'auxiliary target group',
        'encouragement',
        'invitation ',
        'invitation'
    ],
    "contact": [
        'contact details',
        'contact person',
        'contact info',
        'contact',
        'contact practicalities ',
        'contact person name ',
        'contact person title ',
        'contact person mail ',
        'job contact information',
        'job inquiry email',
        'phone number',
        'contacts',
        'contact ddetails',
        'help',
        'signature ',
        'contact ',
        'contact person title',
        'details',
        'contact information'
    ],
    "benefits / offerings": [
        'benefits',
        'reward',
        'treats',
        'job benefits',
        "company's treats",
        'opportunities',
        'additional job opportunities',
        'incentive',
        'additional opportunity',
        'salary',
        'offering',
        'we offer',
        'job offer',
        'compensation',
        'oppoturnity',
        'what you get',
        'offer'
    ],
    "job title": [
        'job title ',
        'seniormanager',
        'clinicalcontractcoordinator',
        'search',
        'ask',
        'what',
        'work title',
        'need',
        'looking for',
        'title',
        'job title'
    ],
    "recruiting agency": [
        'recruiter',
        'recruiting',
        'contact agent',
        'job agent',
        'about job agent ',
        'about job agent'
    ],
    "why should you apply": [
        'marketing the job',
        'goal',
        'selling the job',
        'marketing of the company',
        'sales pitch',
        'remuneration',
        'motivation',
        'self-advertising',
    ],
    "tags": [
         'keywords'
    ],
    "info": [
         'information',
         'info'
    ]
}

with open('../data/labels_grouped.pickle', 'wb') as handle:
  pickle.dump(labels_grouped, handle)
